apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flink-stream-app.fullname" . }}-runtime
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "flink-stream-app.fullname" . }}
    app.kubernetes.io/component: config
data:
  runtime.env: |
    KAFKA_BOOTSTRAP_SERVERS={{ .Values.kafka.bootstrapServers }}
    KAFKA_INPUT_TOPIC={{ .Values.kafka.inputTopic }}
    KAFKA_CONSUMER_GROUP={{ .Values.kafka.consumerGroup }}
    PAIMON_CATALOG={{ .Values.paimon.catalogName }}
    PAIMON_WAREHOUSE={{ .Values.paimon.warehouse }}
    FLINK_CHECKPOINTS_DIR={{ .Values.state.checkpointsDir }}
    FLINK_SAVEPOINTS_DIR={{ .Values.state.savepointsDir }}
    FLINK_HA_STORAGE_DIR={{ .Values.state.haStorageDir }}
