apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.flink.serviceAccount }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "flink-stream-app.fullname" . }}
